- id: HotorNotStatsDisplay
  name: HotorNot Match History
  metadata:
    description: Formats Hot or Not Match history info and adds streaks.
  version: 1.0
  date:
  path: https://github.com/Servbot91/HotorNot-Stat-Addon/raw/refs/heads/main/plugins/HotorNotStats.zip
  sha256: 12561ABF549AC2D19F00F2B00F3DC62217C9E26B23FDBBB9C4E57F064332D98B
